import {chromium} from 'playwright';import assert from 'node:assert/strict';
const b=await chromium.launch({channel:'msedge',headless:true});const c=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.route('**/api/profile',r=>r.fulfill({json:{enabled:false,mode:'local'}}));
const ratings=['AI','ROBOTICS','XR','DEV','HARDWARE','STARTUPS','SCIENCE'].map((category,i)=>({category,rated_posts:i===0?10:0,likes:i===0?7:0,dislikes:i===0?3:0,preference_score:i===0?64.29:50,average_dwell_ms:3000}));
await p.route('**/api/ratings',r=>r.fulfill({json:{enabled:true,ratings}}));
await p.goto('http://127.0.0.1:3017');await p.getByRole('button',{name:'Like',exact:true}).waitFor();await p.locator('.swipe-card').waitFor();
await p.getByRole('tab',{name:'Analytics',exact:true}).click();await p.getByText('70% geliket',{exact:true}).waitFor();assert.equal(await p.locator('.category-ratings article').count(),7);assert.equal(await p.locator('.metric-grid strong').allTextContents().then(v=>v.join(',')),'10,7,3');await p.screenshot({path:'preview-tinder-analytics.png'});
await p.getByRole('tab',{name:'Ontdek',exact:true}).click();const box=await p.locator('.embed-toolbar>span').boundingBox();const d=await c.newCDPSession(p);await d.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+10,y:box.y+8}]});for(let x=30;x<180;x+=25)await d.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+x,y:box.y+8}]});await d.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(350);assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('techer-v2')).interactions.length),1);
await p.getByRole('button',{name:'Vorige swipe herstellen'}).click();assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('techer-v2')).interactions.length),0);
for(const [width,height] of [[390,844],[320,568],[1440,1000]]){await p.setViewportSize({width,height});const r=await p.getByRole('button',{name:'Like',exact:true}).boundingBox();assert.ok(r.y+r.height<=height,`controls fit ${width}`);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(width===390){await p.waitForTimeout(2500);await p.screenshot({path:'preview-tinder-feed.png'})}}
assert.deepEqual(errors,[]);console.log('PASS: analytics counts and categories, mobile touch swipe and undo, 320/390/1440 layouts, no client errors. Analytics fixture used; no real user data changed.');await b.close();
