'use client';
import {useState} from 'react';
import type {JevAnalysis} from '@/lib/jev-analysis';
const names:Record<string,string>={AI:'AI',ROBOTICS:'Robotics',XR:'XR',DEV:'Dev',HARDWARE:'Hardware',STARTUPS:'Startups',SCIENCE:'Science',TECHNICAL:'Technische diepgang',RESEARCH:'Onderzoek',PRACTICAL:'Praktisch nut',NOVELTY:'Nieuwe technologie'};
type Row={category:string;likes:number;superlikes?:number;dislikes:number;rated_posts:number;average_dwell_ms:number};
export function AnalysisCharts({analysis,rows}:{analysis:JevAnalysis;rows:Row[]}){
 const [selected,setSelected]=useState(analysis.categories[0]?.category??'AI');
 const scores=analysis.categories,active=scores.find(c=>c.category===selected),observed=rows.find(r=>r.category===selected);
 const point=(i:number,value:number)=>{const a=i/scores.length*Math.PI*2-Math.PI/2;return `${180+Math.cos(a)*value},${160+Math.sin(a)*value}`};
 return <div className="analysis-charts"><div className="chart-panel"><h3>Je tech-profiel</h3><p>JEV-voorkeur per categorie · 0–100</p><svg viewBox="0 0 360 330" role="img" aria-label="Radar van JEV-voorkeuren; exacte waarden staan in de tabel hieronder">{[.25,.5,.75,1].map(level=><polygon key={level} points={scores.map((_,i)=>point(i,112*level)).join(' ')} fill="none" stroke="#413649"/>)}{scores.map((c,i)=><line key={c.category} x1="180" y1="160" x2={point(i,112).split(',')[0]} y2={point(i,112).split(',')[1]} stroke="#413649"/>)}<polygon points={scores.map((c,i)=>point(i,c.score*1.12)).join(' ')} fill="#d361bd44" stroke="#ec73bd" strokeWidth="2.5"/>{scores.map((c,i)=><text key={c.category} x={point(i,140).split(',')[0]} y={Number(point(i,140).split(',')[1])+4} textAnchor="middle" fill="#d8c9e2" fontSize="11">{names[c.category]}</text>)}</svg><div className="chart-picker" aria-label="Categorie bekijken">{scores.map(c=><button key={c.category} aria-pressed={selected===c.category} onClick={()=>setSelected(c.category)}>{names[c.category]}</button>)}</div>{active&&<p className="chart-insight"><b>{names[selected]} · {active.score}/100</b><br/>{observed?.rated_posts?`${observed.likes} likes, ${observed.superlikes??0} superlikes en ${observed.dislikes} dislikes in je volledige geschiedenis.`:'Nog geen swipes in deze categorie.'} JEV-confidence: {Math.round(active.confidence*100)}%. Een score van 50 kan ook onvoldoende bewijs betekenen.</p>}</div>
 {!!analysis.dimensions?.length&&<div className="chart-panel"><h3>Wat je zoekt in een post</h3><p>Door JEV geschat uit dezelfde swipe-selectie.</p>{analysis.dimensions.map(d=><div className="dimension" key={d.category}><div><span>{names[d.category]}</span><b>{d.score}/100</b></div><div className="dimension-track"><i style={{width:`${d.score}%`}}/></div><small>Confidence {Math.round(d.confidence*100)}%</small></div>)}</div>}
 <div className="chart-panel"><h3>Gedrag tegenover JEV</h3><p>Gedrag: alle opgeslagen swipes. JEV: laatste {analysis.swipesUsed}. Verschillen zijn geen meetfouten.</p><div className="analysis-table-scroll"><table><caption>Voorkeuren en waarnemingen per categorie</caption><thead><tr><th>Categorie</th><th>Dislike / like / superlike</th><th>Like %</th><th>JEV</th><th>Confidence</th><th>Kaarttijd</th></tr></thead><tbody>{scores.map(c=>{const r=rows.find(v=>v.category===c.category);return <tr key={c.category}><th scope="row">{names[c.category]}</th><td>{r?`${r.dislikes} / ${r.likes} / ${r.superlikes??0}`:'0 / 0'}</td><td>{r?.rated_posts?`${Math.round((r.likes+(r.superlikes??0))/r.rated_posts*100)}%`:'—'}</td><td>{c.score}</td><td>{Math.round(c.confidence*100)}%</td><td>{r?.rated_posts?`${(Number(r.average_dwell_ms)/1000).toFixed(1)}s`:'—'}</td></tr>})}</tbody></table></div><p>Kaarttijd is de gemiddelde tijd tot een swipe, geen gemeten leestijd. Confidence is zekerheid van het model, geen hoeveelheid bewijs.</p></div></div>;
}
