'use client';
import {useState} from 'react';
import type {JevAnalysis} from '@/lib/jev-analysis';
const names:Record<string,string>={AI:'AI',ROBOTICS:'Robotics',XR:'XR',DEV:'Dev',HARDWARE:'Hardware',STARTUPS:'Startups',SCIENCE:'Science'};
export function AnalysisHistory({analysis,history}:{analysis:JevAnalysis;history:JevAnalysis[]}){
 const [category,setCategory]=useState('AI');
 const points=[...history].sort((a,b)=>Date.parse(a.createdAt)-Date.parse(b.createdAt)).filter(a=>a.categories.some(c=>c.category===category));
 const start=Date.parse(points[0]?.createdAt??analysis.createdAt),end=Date.parse(points.at(-1)?.createdAt??analysis.createdAt);
 const x=(at:string)=>30+(end===start?.5:(Date.parse(at)-start)/(end-start))*300;
 const y=(n:number)=>150-n*1.2;
 const evidence=analysis.evidence;
 return <div className="chart-panel"><h3>Voorkeuren door de tijd</h3><p>{history.length} opgeslagen analyses · maximaal de laatste 90 getoond</p><select aria-label="Categorie voor analysegeschiedenis" value={category} onChange={e=>setCategory(e.target.value)} style={{background:'#211929',padding:10,borderRadius:8,color:'white'}}>{Object.entries(names).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select>{points.length>1?<svg viewBox="0 0 360 185" role="img" aria-label={`JEV-score voor ${names[category]} over tijd`}>{[0,50,100].map(v=><g key={v}><line x1="30" x2="330" y1={y(v)} y2={y(v)} stroke="#44364c"/><text x="3" y={y(v)+4} fill="#aa9ab4" fontSize="10">{v}</text></g>)}<polyline points={points.map(p=>`${x(p.createdAt)},${y(p.categories.find(c=>c.category===category)!.score)}`).join(' ')} fill="none" stroke="#f374ba" strokeWidth="2"/>{points.map(p=><circle key={p.createdAt} cx={x(p.createdAt)} cy={y(p.categories.find(c=>c.category===category)!.score)} r="3" fill="#f374ba"><title>{new Date(p.createdAt).toLocaleString('nl-NL')}: {p.categories.find(c=>c.category===category)!.score}/100</title></circle>)}<text x="30" y="175" fill="#aa9ab4" fontSize="10">{new Date(start).toLocaleDateString('nl-NL')}</text><text x="330" y="175" textAnchor="end" fill="#aa9ab4" fontSize="10">{new Date(end).toLocaleDateString('nl-NL')}</text></svg>:<p>Na je tweede analyse verschijnt hier een trendlijn. Eerdere overschreven analyses kunnen niet worden teruggehaald.</p>}
 <details><summary>Meetpunten bekijken</summary><div className="analysis-table-scroll"><table><thead><tr><th>Datum</th><th>JEV-score</th><th>Versie</th></tr></thead><tbody>{points.map(p=><tr key={p.createdAt}><td>{new Date(p.createdAt).toLocaleString('nl-NL')}</td><td>{p.categories.find(c=>c.category===category)?.score}</td><td>{p.version??1}</td></tr>)}</tbody></table></div></details>
 {evidence&&<><h3 style={{marginTop:24}}>Hoeveel bewijs is er?</h3><p>{evidence.total} swipes over {evidence.activeDays} actieve dagen. JEV krijgt deze historische samenvatting plus de laatste {analysis.swipesUsed} postfragmenten.</p><div className="analysis-table-scroll"><table><thead><tr><th>Categorie</th><th>Totaal</th><th>Laatste 30d</th><th>Vorige 30d</th><th>Verschil</th></tr></thead><tbody>{evidence.categories.map(c=><tr key={c.category}><th>{names[c.category]}</th><td>{c.lifetime.count}</td><td>{c.recent30.count?`${Math.round(c.recent30.likes/c.recent30.count*100)}% (${c.recent30.count})`:'—'}</td><td>{c.previous30.count?`${Math.round(c.previous30.likes/c.previous30.count*100)}% (${c.previous30.count})`:'—'}</td><td>{c.change===null?'Te weinig data':`${c.change>0?'+':''}${c.change} pp`}</td></tr>)}</tbody></table></div><p>Percentages zijn waargenomen likes, geen JEV-scores. Verschillen verschijnen pas bij minimaal vijf swipes in beide periodes en zijn beschrijvend, niet statistisch bewezen. Meer gegevens maken patronen beter te beoordelen, maar garanderen geen betere voorspellingen.</p></>}
 <p>Andere model- of analyseversies kunnen scores beïnvloeden. Dit is geen automatische training van JEV.</p></div>;
}
