'use client';
import {usePersonalModel} from '@/lib/use-personal-model';
import {MIN_LABELS,NEW_LABELS} from '@/lib/personal-model';
const date=(v:string)=>new Date(v).toLocaleDateString('nl-NL',{day:'numeric',month:'short'});
function Progress({label,value,target}:{label:string;value:number;target:number}){return <div className="model-progress"><div><span>{label}</span><strong>{value} <small>/ {target}</small>{value>=target?' ✓':''}</strong></div><progress aria-label={label} value={Math.min(value,target)} max={target}/></div>}
export function ModelPanel(){
 const data=usePersonalModel();
 if(!data)return <section className="chart-panel model-dashboard"><h3>Jouw aanbevelingsmodel</h3><p>Modelstatus wordt opgehaald. Als dit niet lukt, blijft je feed beschikbaar.</p></section>;
 const {active,state,available,history,positive,negative,newLabels}=data,m=state?.metrics;
 const ready=available>=MIN_LABELS&&positive>=15&&negative>=15,updating=!!active||state?.status==='rejected';
 const remaining=Math.max(0,updating?NEW_LABELS-newLabels:MIN_LABELS-available);
 const title=data.invalidated?'Je keuzes zijn veranderd':active?'Je feed leert van jou':state?.status==='rejected'?'We wachten op een beter model':ready?'Klaar voor de volgende controle':'Leer Techer jouw smaak';
 const description=data.invalidated?'Je eerdere model wordt opnieuw beoordeeld. Tot die tijd gebruiken we de basisrangschikking.':active?'Je persoonlijke model bepaalt mee welke posts je als eerste ziet.':state?.status==='rejected'?'De laatste kandidaat was niet duidelijk beter. Je huidige rangschikking blijft behouden.':ready?'Er zijn genoeg keuzes voor een trainingspoging. De dagelijkse controle kijkt ook of een eerlijke test mogelijk is.':'Elke beoordeling helpt je persoonlijke model. Een superlike telt als een sterkere voorkeur.';
 const losses=m?[{label:'Nieuwe kandidaat',value:m.candidate},{label:'Basisvoorspelling',value:m.baseline},...(m.incumbent===null?[]:[{label:'Vorig model',value:m.incumbent}])]:[],maxLoss=Math.max(...losses.map(l=>l.value),.001);
 return <section className="chart-panel model-dashboard" aria-label="Jouw aanbevelingsmodel">
 <header className="model-header"><span className="eyebrow">JOUW AANBEVELINGSMODEL</span><span className="model-badge">{active?'Persoonlijk actief':'Basisfeed actief'}</span></header>
 <h3>{title}</h3><p>{description}</p>
 <div className="model-hero"><strong>{updating?newLabels:available}<span> / {updating?NEW_LABELS:MIN_LABELS}</span></strong><span>{updating?'nieuwe beoordelingen':'unieke posts beoordeeld'}</span><progress aria-label="Voortgang naar trainingsdrempel" value={Math.min(updating?newLabels:available,updating?NEW_LABELS:MIN_LABELS)} max={updating?NEW_LABELS:MIN_LABELS}/><p>{remaining>0?`Nog ${remaining} posts tot de ${updating?'volgende':'eerste'} trainingsdrempel.`:'Trainingsdrempel bereikt.'}</p></div>
 <div className="model-requirements"><Progress label="Likes + superlikes" value={positive} target={15}/><Progress label="Dislikes" value={negative} target={15}/></div>
 <p className="model-hint">Beoordeel op je eigen smaak. Je hoeft niets te liken om een drempel te halen.</p>
 <ol className="model-steps"><li data-done={ready}><b>01</b><strong>Verzamelen</strong><span>Jouw keuzes</span></li><li data-done={!!m}><b>02</b><strong>Testen</strong><span>Op aparte posts</span></li><li data-done={!!active}><b>03</b><strong>Verbeteren</strong><span>Alleen bij winst</span></li></ol>
 {m?<div className="model-test"><div className="model-test-heading"><h4>Laatste modeltest</h4><span>{m.testCount} testposts</span></div><p>{state?.status==='active'?'Kandidaat toegelaten':'Geen nieuw model geactiveerd'} · {date(m.testStart)} – {date(m.testEnd)}</p><div className="model-losses" role="img" aria-label={'Voorspelfout, lager is beter. '+losses.map(l=>`${l.label}: ${l.value.toFixed(3)}`).join('. ')}>{losses.map(l=><div key={l.label}><div><span>{l.label}</span><strong>{l.value.toFixed(3)}</strong></div><div className="model-loss-track"><i style={{width:`${l.value/maxLoss*100}%`}}/></div></div>)}</div><p className="model-hint">Lagere voorspelfout is beter. Activatie vereist minstens 2% winst tegenover de basis én een eventueel vorig model. Dit garandeert nog geen betere hele feed.</p></div>:<div className="model-test"><h4>De eerste test volgt nog</h4><p>Hier vergelijk je straks het nieuwe model met de basis. Er zijn nog geen testresultaten.</p></div>}
 <footer className="model-footer"><span>Dagelijkse controle</span><span>{data.checkedAt?`Laatst: ${date(data.checkedAt)}`:'Nog niet gecontroleerd'}</span></footer>
 <details><summary>Hoe het leert & trainingsgeschiedenis</summary><p>Het model leert van categorieën, tags en tekst. Nieuwere keuzes wegen zwaarder. Na 20 nieuwe beoordelingen kan het opnieuw trainen. Een bruikbare verdeling van likes en dislikes in de test blijft nodig. Ongelezen posts en bookmarks tellen niet als dislikes.</p><p>JEV maakt apart de inhoudelijke analyse. Dit model traint JEV zelf niet. Een persoonlijk model verkent ongeveer één op zeven posities andere posts.</p>{active&&<p>Actief model getraind op {active.trainedCount} posts · {date(active.trainedAt)}.</p>}{state&&<p>Laatste controle: {state.reason}</p>}{m&&<p>Test vóór de definitieve training: {m.trainCount} trainingsposts en {m.testCount} apart gehouden testposts. De grafiek toont log loss op gewogen ratings. Na toelating traint het model opnieuw op alle beschikbare voorbeelden.</p>}{history.length>0?<div className="analysis-table-scroll"><table><caption>Laatste {history.length} controles</caption><thead><tr><th>Datum</th><th>Uitkomst</th><th>Voorspelfout</th></tr></thead><tbody>{history.map((r,i)=><tr key={r.created_at+i}><th>{date(r.created_at)}</th><td>{r.state.status==='active'?'Geactiveerd':r.state.status==='rejected'?'Niet beter':'Meer keuzes nodig'}</td><td>{r.state.metrics?.candidate.toFixed(3)??'—'}</td></tr>)}</tbody></table></div>:<p>Nog geen trainingsgeschiedenis.</p>}</details>
 </section>;
}
