'use client';
import {usePersonalModel} from '@/lib/use-personal-model';
export function ModelPanel(){const data=usePersonalModel();if(!data)return <div className="chart-panel"><h3>Persoonlijk model</h3><p>Modelstatus laden of tijdelijk niet beschikbaar. De gewone feed blijft werken.</p></div>;
 const {active,state,available,history}=data,m=state?.metrics;
 return <div className="chart-panel"><span className="eyebrow">AUTOMATISCH LEREN</span><h3>Jouw aanbevelingsmodel</h3><p>{active?'Persoonlijke rangschikking actief':data.invalidated?'Model opnieuw beoordelen na gewijzigde swipes':'De gewone rangschikking is actief'}</p><p>{available} unieke beoordeelde posts · eerste training vanaf 100, met minstens 15 likes en 15 dislikes.</p><div className="dimension-track" role="progressbar" aria-label="Voortgang naar eerste training" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.min(100,available)}><i style={{width:`${Math.min(100,available)}%`}}/></div><p>{state?.reason??'De dagelijkse controle start zodra je profiel is opgeslagen.'}</p>{state&&<p>Laatst gecontroleerd: {new Date(state.checkedAt).toLocaleString('nl-NL')}</p>}{active&&<p>Model v{active.version} · getraind op {active.trainedCount} posts · {new Date(active.trainedAt).toLocaleString('nl-NL')}</p>}
 {m&&<><h3>Laatste onafhankelijke test</h3><div className="analysis-table-scroll"><table><thead><tr><th>Voorspeller</th><th>Log loss ↓</th></tr></thead><tbody><tr><th>Kandidaat</th><td>{m.candidate.toFixed(3)}</td></tr><tr><th>Basisvoorspelling</th><td>{m.baseline.toFixed(3)}</td></tr><tr><th>Vorig model</th><td>{m.incumbent?.toFixed(3)??'—'}</td></tr></tbody></table></div><p>{m.testCount} recente posts apart gehouden; {Math.round(m.accuracy*100)}% juiste like/dislike-keuzes. Lagere log loss betekent betere kansvoorspellingen op deze test. Dit bewijst nog geen verbetering van de hele feed.</p></>}
 <p>Dagelijkse controle. Opnieuw trainen vanaf 20 nieuwe posts. Nieuwere swipes wegen zwaarder; circa één op zeven posities verkent andere posts. Niet-getoonde posts en bookmarks zijn geen negatieve trainingsvoorbeelden.</p><p>Het model leert lokaal op de server van categorieën, tags en tekst. JEV verzorgt apart je inhoudelijke analyse; JEV wordt hiermee niet gefinetuned.</p>
 {!!history.length&&<details><summary>Trainingsgeschiedenis ({history.length})</summary>{history.map(r=><p key={r.created_at}>{new Date(r.created_at).toLocaleString('nl-NL')} · {r.state.status==='active'?'Geactiveerd':'Niet geactiveerd'}{r.state.metrics?` · verlies ${r.state.metrics.candidate.toFixed(3)}`:''}</p>)}</details>}</div>;
}
