'use client';
import {useLanguage} from '@/lib/i18n';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight} from 'lucide-react';
import type {Post} from '@/lib/radar';
import {xPostId,type XPost} from '@/lib/x-post';
const cache=new Map<string,Promise<XPost|null>>();
export function preloadPost(url:string){const id=xPostId(url);if(!id)return Promise.resolve(null);let p=cache.get(id);if(!p){p=fetch(`/api/post?id=${id}`).then(async r=>r.ok?await r.json() as XPost:null).catch(()=>null);cache.set(id,p);if(cache.size>150)cache.delete(cache.keys().next().value!)}return p}
function PostLinks({text}:{text:string}){return <>{text.split(/(https?:\/\/[^\s]+|@[A-Za-z0-9_]+)/g).map((part,i)=>/^https?:\/\//.test(part)?<a key={i} href={part} target="_blank" rel="noopener noreferrer">{part.replace(/^https?:\/\//,'')}</a>:/^@[A-Za-z0-9_]+$/.test(part)?<a key={i} href={'https://x.com/'+part.slice(1)} target="_blank" rel="noopener noreferrer">{part}</a>:part)}</>}
export function PostText({post,onRead}:{post:Post;onRead:()=>void}){
 const {t,locale,language}=useLanguage();

 const id=xPostId(post.url);const [result,setResult]=useState<XPost|null>(null),[pending,setPending]=useState(Boolean(id));
 useEffect(()=>{let active=true;setResult(null);setPending(Boolean(id));if(id)void preloadPost(post.url).then(data=>{if(active){setResult(data);setPending(false)}});return()=>{active=false}},[post.id,id,post.url]);
 const name=result?.author||post.author.replace(/^@/,'');const initials=name.split(/\s+/).filter(Boolean).slice(0,2).map(n=>n[0]).join('').toUpperCase();const profileUrl=id?'https://x.com/'+post.author.replace(/^@/,''):post.url;
 return <><div className="x-author"><a className="x-avatar" href={profileUrl} target="_blank" rel="noopener noreferrer" aria-label={t("Profiel van ")+name}>{initials}</a><div className="x-identity"><a href={profileUrl} target="_blank" rel="noopener noreferrer" className="x-display-name">{name}</a><span>{post.author}</span></div>{id&&<a className="x-platform" href={post.url} target="_blank" rel="noopener noreferrer" aria-label={t("Open op X")}>𝕏</a>}</div>{result?<><h1 className="sr-only">{post.title}</h1><p className="original-text"><PostLinks text={result.text}/></p>{result.truncated&&<a className="x-show-more" href={post.url} target="_blank" rel="noopener noreferrer">{""}{t("Meer weergeven op X")}{' '}<ArrowUpRight size={14}/></a>}<button className="read-original" onClick={onRead}><span>{""}{t("Originele post")}{' '}</span><span>{""}{t("Foto’s, video’s en geciteerde posts")}{' '}</span><ArrowUpRight size={18}/></button>{result.truncated&&<p className="post-limitation">{""}{t("X levert voor deze lange post een verkorte weergave.")}{' '}</p>}</>:<><h1 className="x-feed-title">{post.title}</h1>{post.text&&<p className="post-excerpt"><PostLinks text={post.text}/></p>}<p className="post-limitation" role="status">{id?(pending?t("Originele post laden…"):t("X-post niet beschikbaar. Fragment via Aligned News.")):t("Fragment via Aligned News.")}</p>{id&&<button className="read-original" onClick={onRead}><span>{""}{t("Originele post")}{' '}</span><span>{""}{t("Bekijk op X")}{' '}</span><ArrowUpRight size={18}/></button>}</>}<div className="x-timestamp">{""}{t("In feed ·")}{' '}{new Intl.DateTimeFormat(locale,{day:'numeric',month:'short',year:'numeric'}).format(new Date(post.publishedAt))}<span> · {post.tags.join(' · ')}</span></div></>
}

type Widgets={widgets:{createTweet:(id:string,element:HTMLElement,options:Record<string,unknown>)=>Promise<HTMLElement|undefined>}};
let scriptPromise:Promise<Widgets>|null=null;
function loadWidgets(){if(scriptPromise)return scriptPromise;scriptPromise=new Promise<Widgets>((resolve,reject)=>{const existing=(window as Window&{twttr?:Widgets}).twttr;if(existing?.widgets){resolve(existing);return}const script=document.createElement('script');script.src='https://platform.twitter.com/widgets.js';script.async=true;script.id='techer-x-widgets';const timeout=setTimeout(()=>reject(Error('X timeout')),12000);script.onload=()=>{clearTimeout(timeout);const w=(window as Window&{twttr?:Widgets}).twttr;w?.widgets?resolve(w):reject(Error('X unavailable'))};script.onerror=()=>{clearTimeout(timeout);reject(Error('X unavailable'))};document.head.appendChild(script)});return scriptPromise}
export function OriginalEmbed({post}:{post:Post}){
 const {t,locale,language}=useLanguage();
const mount=useRef<HTMLDivElement>(null);const [state,setState]=useState('loading');const id=xPostId(post.url);useEffect(()=>{const host=mount.current;if(!host||!id){setState('error');return}let live=true;let timedOut=false;setState('loading');host.replaceChildren();const container=document.createElement('div');host.appendChild(container);const t=setTimeout(()=>{timedOut=true;if(live)setState('error')},15000);void loadWidgets().then(w=>w.widgets.createTweet(id,container,{lang:language,theme:'dark',dnt:true,conversation:'none',align:'center'})).then(el=>{if(live&&!timedOut)setState(el?'loaded':'error')}).catch(()=>{if(live)setState('error')}).finally(()=>clearTimeout(t));return()=>{live=false;clearTimeout(t);container.remove()}},[id,language]);return <div className="original-embed">{state==='loading'&&<p className="embed-status" role="status">{""}{t("Originele X-post laden…")}{' '}</p>}<div ref={mount}/>{state==='error'&&<div className="embed-status"><p>{""}{t("X kan dit bericht hier niet laden.")}{' '}</p><a className="primary" href={post.url} target="_blank" rel="noopener noreferrer">{""}{t("Lees de post op X ↗")}{' '}</a></div>}</div>}
