'use client';
import {useEffect,useRef,useState} from 'react';
import type {Post} from '@/lib/radar';
import {xPostId,type XPost} from '@/lib/x-post';
const cache=new Map<string,Promise<XPost|null>>();
export function preloadPost(url:string){const id=xPostId(url);if(!id)return Promise.resolve(null);let p=cache.get(id);if(!p){p=fetch(`/api/post?id=${id}`).then(async r=>r.ok?await r.json() as XPost:null).catch(()=>null);cache.set(id,p);if(cache.size>150)cache.delete(cache.keys().next().value!)}return p}
export function PostText({post,onRead}:{post:Post;onRead:()=>void}){const id=xPostId(post.url);const [result,setResult]=useState<XPost|null>(null),[pending,setPending]=useState(Boolean(id));useEffect(()=>{let active=true;setResult(null);setPending(Boolean(id));if(id)void preloadPost(post.url).then(data=>{if(active){setResult(data);setPending(false)}});return()=>{active=false}},[post.id,id,post.url]);return <><span className="post-author">{result?`${result.author} · ${post.author}`:post.author}</span>{result?<><h1 className="sr-only">{post.title}</h1>{result.truncated&&<p className="post-limitation">X-preview van een lange post. <a href={post.url} target="_blank" rel="noopener noreferrer">Volledig op X ↗</a></p>}<p className="original-text">{result.text}</p><button className="read-original" onClick={onRead}>Bekijk X-post met media ↗</button></>:<><h1 className={post.title.length>160?'long-title':''}>{post.title}</h1>{post.text&&<p className="post-excerpt">{post.text}</p>}<p className="post-limitation" role="status">{id?(pending?'Originele post laden…':'X-post niet beschikbaar. Dit is het fragment van Aligned News.'):'Dit is het bericht uit de feed. De volledige publicatie staat op de bronwebsite.'}</p>{id&&<button className="read-original" onClick={onRead}>Bekijk X-post ↗</button>}</>}</>}
type Widgets={widgets:{createTweet:(id:string,element:HTMLElement,options:Record<string,unknown>)=>Promise<HTMLElement|undefined>}};
let scriptPromise:Promise<Widgets>|null=null;
function loadWidgets(){if(scriptPromise)return scriptPromise;scriptPromise=new Promise<Widgets>((resolve,reject)=>{const existing=(window as Window&{twttr?:Widgets}).twttr;if(existing?.widgets){resolve(existing);return}const script=document.createElement('script');script.src='https://platform.twitter.com/widgets.js';script.async=true;script.id='techer-x-widgets';const timeout=setTimeout(()=>reject(Error('X timeout')),12000);script.onload=()=>{clearTimeout(timeout);const w=(window as Window&{twttr?:Widgets}).twttr;w?.widgets?resolve(w):reject(Error('X unavailable'))};script.onerror=()=>{clearTimeout(timeout);reject(Error('X unavailable'))};document.head.appendChild(script)});return scriptPromise}
export function OriginalEmbed({post}:{post:Post}){const mount=useRef<HTMLDivElement>(null);const [state,setState]=useState('loading');const id=xPostId(post.url);useEffect(()=>{const host=mount.current;if(!host||!id){setState('error');return}let live=true;let timedOut=false;setState('loading');host.replaceChildren();const container=document.createElement('div');host.appendChild(container);const t=setTimeout(()=>{timedOut=true;if(live)setState('error')},15000);void loadWidgets().then(w=>w.widgets.createTweet(id,container,{theme:'dark',dnt:true,conversation:'none',align:'center'})).then(el=>{if(live&&!timedOut)setState(el?'loaded':'error')}).catch(()=>{if(live)setState('error')}).finally(()=>clearTimeout(t));return()=>{live=false;clearTimeout(t);container.remove()}},[id]);return <div className="original-embed">{state==='loading'&&<p className="embed-status" role="status">Originele X-post laden…</p>}<div ref={mount}/>{state==='error'&&<div className="embed-status"><p>X kan dit bericht hier niet laden.</p><a className="primary" href={post.url} target="_blank" rel="noopener noreferrer">Lees de post op X ↗</a></div>}<p className="small-print">Originele weergave van X. Bij lange posts kan X ‘Meer weergeven’ tonen.</p></div>}
