'use client';
type Rating={category:string;rated_posts:number;likes:number;dislikes:number;superlikes:number;preference_score:number};
export type Activity={date:string;dislike:number;like:number;superlike:number};
export function RatingsOverview({rows,activity}:{rows:Rating[];activity:Activity[]}){
 const total=rows.reduce((n,r)=>n+r.rated_posts,0),likes=rows.reduce((n,r)=>n+r.likes,0),superlikes=rows.reduce((n,r)=>n+(r.superlikes??0),0),dislikes=total-likes-superlikes;
 const first=total?dislikes/total*100:0,second=total?(dislikes+likes)/total*100:0,max=Math.max(1,...activity.map(d=>d.dislike+d.like+d.superlike));
 const leaders=[...rows].filter(r=>r.rated_posts>=3).sort((a,b)=>Number(b.preference_score)-Number(a.preference_score)).slice(0,3);
 return <div className="rating-overview"><div className="rating-hero"><div className="rating-donut" role="img" aria-label={`${dislikes} dislikes, ${likes} likes, ${superlikes} superlikes`} style={{background:total?`conic-gradient(#fa7185 0 ${first}%,#d16bd7 ${first}% ${second}%,#56b5ff ${second}% 100%)`:'#342c3c'}}><div><strong>{total}</strong><span>waarderingen</span></div></div><div className="rating-legend"><p><i style={{background:'#fa7185'}}/>Dislike <b>{dislikes}</b></p><p><i style={{background:'#d16bd7'}}/>Like <b>{likes}</b></p><p><i style={{background:'#56b5ff'}}/>Superlike <b>{superlikes}</b></p></div></div><div className="chart-panel"><h3>De afgelopen 14 dagen</h3><p>Jouw activiteit · dagen in UTC</p><div className="activity-chart" role="img" aria-label={activity.map(d=>`${d.date}: ${d.like} likes, ${d.superlike} superlikes, ${d.dislike} dislikes`).join('; ')}>{activity.map(d=><div key={d.date} className="activity-day" title={`${d.date}: ${d.dislike+d.like+d.superlike} waarderingen`}><div className="activity-stack"><i style={{height:`${d.superlike/max*100}%`,background:'#56b5ff'}}/><i style={{height:`${d.like/max*100}%`,background:'#d16bd7'}}/><i style={{height:`${d.dislike/max*100}%`,background:'#fa7185'}}/></div><small>{d.date.slice(-2)}</small></div>)}</div><details><summary>Dagcijfers bekijken</summary><div className="analysis-table-scroll"><table><thead><tr><th>Datum</th><th>Dislike</th><th>Like</th><th>Superlike</th></tr></thead><tbody>{activity.map(d=><tr key={d.date}><th>{d.date}</th><td>{d.dislike}</td><td>{d.like}</td><td>{d.superlike}</td></tr>)}</tbody></table></div></details></div><div className="chart-panel"><h3>Wat springt eruit?</h3>{leaders.length?<><p>Je hoogst gewaardeerde categorieën, vanaf drie keuzes per categorie:</p>{leaders.map((r,i)=><p key={r.category}><b>{i+1}. {r.category}</b> · score {Math.round(Number(r.preference_score))}/100 · {r.superlikes??0} superlikes uit {r.rated_posts} keuzes</p>)}</>:<p>Beoordeel minstens drie posts in een categorie om hier je eerste patroon te zien.</p>}<p>Dislike = 0, like = 1, superlike = 2. De categoriescore gebruikt deze schaal met een neutrale start. Dit zijn jouw keuzes; de JEV-schatting staat apart hieronder.</p></div></div>;
}
