import {XMLParser} from 'fast-xml-parser';
import type {Post,Category} from './radar';
export const ALIGNED_FEED='https://alignednews.com/feed.xml';
const map:Record<string,Category>={agents:'AI',models:'AI',openclaw:'AI',chips:'HARDWARE',robotics:'ROBOTICS',xr:'XR',spatial:'XR',dev:'DEV',coding:'DEV',startups:'STARTUPS',business:'STARTUPS',science:'SCIENCE',papers:'SCIENCE',infrastructure:'HARDWARE'};
function clean(value:unknown){return String(value??'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}
export function parseAligned(xml:string):Post[]{if(xml.length>2_000_000||/<!DOCTYPE|<!ENTITY/i.test(xml))throw Error('Unsupported feed');const parsed=new XMLParser({ignoreAttributes:true,parseTagValue:false,processEntities:true}).parse(xml);const items=parsed?.rss?.channel?.item;if(!items)throw Error('Invalid RSS');const seen=new Set<string>();return (Array.isArray(items)?items:[items]).flatMap((item:Record<string,unknown>)=>{const title=clean(item.title);const url=clean(item.link);const date=new Date(clean(item.pubDate));if(!title||!/^https?:\/\//.test(url)||!Number.isFinite(date.getTime()))return [];let link:URL;try{link=new URL(url)}catch{return []}link.hash='';for(const key of [...link.searchParams.keys()])if(key.startsWith('utm_'))link.searchParams.delete(key);const id='aligned:'+link.toString();if(seen.has(id))return [];seen.add(id);const sourceCategory=clean(item.category)||'ai';const category:Category=map[sourceCategory]||(sourceCategory==='jobs'?'STARTUPS':sourceCategory.startsWith('events-')&&/robot/i.test(title)?'ROBOTICS':'AI');const body=clean(item.description).replace(/The source presents a concrete development or result worth tracking, with verification centered on the linked primary record and its follow up evidence\.?/gi,'').trim();const trimmedBody=body.replace(/The linked primary post supplies the specific claim and context that readers should evaluate\.?/gi,'').trim();const text=trimmedBody.toLowerCase().startsWith(title.toLowerCase())?trimmedBody.slice(title.length).replace(/^[.\s]+/,'').trim():trimmedBody;const all=(title+' '+text).toLowerCase();const related:Category[]=[];if(/\b(ai|inference|model|agent|llm|gpu)\b/.test(all)&&category!=='AI')related.push('AI');if(/\b(code|coding|developer|software|api|open.source)\b/.test(all)&&category!=='DEV')related.push('DEV');if(/\b(chip|compute|memory|semiconductor|hardware)\b/.test(all)&&category!=='HARDWARE')related.push('HARDWARE');if(/\b(robot|robotics|embodied)\b/.test(all)&&category!=='ROBOTICS')related.push('ROBOTICS');const isX=['x.com','twitter.com','www.x.com'].includes(link.hostname);const handle=isX?link.pathname.split('/')[1]:'';return [{id,title,text,category,tags:[sourceCategory.replace(/-/g,' ')],author:handle?'@'+handle:link.hostname.replace(/^www\./,''),handle:handle?'@'+handle:'',url:link.toString(),source:'Aligned News',sourceCategory,related,publishedAt:date.toISOString()}]})}
let cached:{posts:Post[];fetchedAt:string}|null=null;let pending:Promise<{posts:Post[];fetchedAt:string;stale:boolean}>|null=null;
export async function fetchAligned(){if(cached&&Date.now()-Date.parse(cached.fetchedAt)<300000)return {...cached,stale:false};if(pending)return pending;pending=(async()=>{try{const response=await fetch(ALIGNED_FEED,{headers:{Accept:'application/rss+xml, application/xml'},signal:AbortSignal.timeout(12000),redirect:'manual'});if(!response.ok)throw Error('Feed unavailable');const xml=await response.text();const posts=parseAligned(xml);if(!posts.length)throw Error('Empty feed');cached={posts,fetchedAt:new Date().toISOString()};return {...cached,stale:false}}catch(error){if(cached)return {...cached,stale:true};throw error}finally{pending=null}})();return pending}

