export const categories = ['AI','ROBOTICS','XR','DEV','HARDWARE','STARTUPS','SCIENCE'] as const;
export type Category = typeof categories[number];
export type Action = 'RIGHT'|'LEFT'|'SAVE'|'OPEN';
export type Post = {id:string;title:string;text:string;category:Category;tags:string[];author:string;handle:string;url:string;source:string;sourceCategory:string;related:Category[];publishedAt:string};
export type Interaction = {id:string;postId:string;category:Category;post?:Post;action:Action;dwellTime:number;createdAt:string};
export type Profile = {interests:Category[];interactions:Interaction[];saved:Post[]};
export const initialProfile:Profile={interests:['AI','DEV'],interactions:[],saved:[]};
export function affinity(profile:Profile,category:Category){return Math.max(-3,Math.min(6,(profile.interests.includes(category)?1:0)+profile.interactions.reduce((n,e)=>n+(e.category===category?{RIGHT:.7,LEFT:-.5,SAVE:0,OPEN:0}[e.action]:0),0)))}
export function rank(posts:Post[],profile:Profile,filter:string){const seen=new Set(profile.interactions.filter(e=>e.action==='RIGHT'||e.action==='LEFT').map(e=>e.postId));return posts.filter(p=>!seen.has(p.id)&&(filter==='ALL'||filter==='BLIND SPOT'||p.category===filter)).map(p=>{const interest=affinity(profile,p.category);const bridge=Math.max(0,...p.related.map(c=>affinity(profile,c)));const freshness=Math.max(0,1-(Date.now()-Date.parse(p.publishedAt))/86400000/7);return {post:p,interest,bridge,score:filter==='BLIND SPOT'?bridge/(1+Math.max(0,interest))+freshness*.1:interest+freshness*.2+(/^https:\/\/(x.com|twitter.com)\//.test(p.url)?.3:0)}}).filter(p=>filter!=='BLIND SPOT'||(p.bridge>0&&p.interest<1)).sort((a,b)=>b.score-a.score).map(p=>p.post)}
export function isPost(value:unknown):value is Post {if(!value||typeof value!=='object')return false;const p=value as Post;return typeof p.id==='string'&&typeof p.title==='string'&&typeof p.text==='string'&&typeof p.url==='string'&&/^https?:\/\//.test(p.url)&&categories.includes(p.category)&&Array.isArray(p.related)&&p.related.every(c=>categories.includes(c))&&Array.isArray(p.tags)&&p.tags.every(t=>typeof t==='string')&&typeof p.author==='string'&&typeof p.source==='string'&&typeof p.sourceCategory==='string'&&typeof p.publishedAt==='string'&&Number.isFinite(Date.parse(p.publishedAt))}

