export const categories = ['AI', 'ROBOTICS', 'XR', 'DEV', 'HARDWARE', 'STARTUPS', 'SCIENCE'] as const;
export type Category = typeof categories[number];
export type Action = 'RIGHT' | 'LEFT' | 'SAVE' | 'OPEN';
export type Post = { id: string; title: string; text: string; category: Category; tags: string[]; author: string; handle: string; initials: string; url: string; source: string; quality: number; novelty: number; related: Category[]; visual: string; publishedAt: string; };
export type Interaction = { postId: string; action: Action; dwellTime: number; createdAt: string };
export type Profile = { interests: Category[]; interactions: Interaction[]; saved: string[]; onboarded: boolean };
export const initialProfile: Profile = {interests: ['AI', 'DEV'], interactions: [], saved: [], onboarded: false};
const seeds: Array<[Category,string,string,string[],Category[],string]> = [
 ['AI','The next interface isn’t a chat box. It’s an agent.','A useful agent needs more than a language model. Give it tools, a clear objective, and a feedback loop — and software starts doing the work with you.',['AI agents','Tool use','Human–AI collaboration'],['DEV','STARTUPS'],'agent'],
 ['HARDWARE','The bottleneck is moving from compute to memory.','Moving data can cost more energy than calculating with it. Memory architecture is a central question for efficient AI inference.',['Semiconductors','AI inference','Memory'],['AI','DEV'],'chip'],
 ['ROBOTICS','Robots learn more when we let them try.','Simulation lets a robot practice a task thousands of times before it touches the real world. The challenge is closing the gap between the two.',['Simulation','Embodied AI','Learning'],['AI','HARDWARE'],'robot'],
 ['DEV','Your tests are the specification an agent can read.','When coding agents can run a reliable test suite, they get something prompts alone cannot provide: a measurable definition of done.',['Coding agents','Testing','Developer tools'],['AI','STARTUPS'],'code'],
 ['XR','Spatial computing needs less interface.','The best spatial interactions may look like ordinary gestures. The design problem is deciding when digital information deserves a place in your physical world.',['Spatial computing','Interaction design'],['HARDWARE','AI'],'spatial'],
 ['STARTUPS','A small team can build a surprisingly large product.','AI tools shorten the path from idea to working software. Distribution, trust, and understanding the customer still decide whether anyone wants it.',['Product strategy','Small teams'],['DEV','AI'],'growth'],
 ['SCIENCE','Better batteries are a software story, too.','Materials discovery combines simulation, laboratory measurements, and machine learning. A better search strategy can change which experiments we run next.',['Materials','Machine learning','Energy'],['AI','HARDWARE'],'science'],
 ['AI','Small models. A much bigger design space.','A model that runs on a device changes the trade-offs around privacy, latency, and connectivity. Bigger is not the only way to make AI useful.',['On-device AI','Privacy','Small models'],['HARDWARE','XR'],'chip'],
 ['ROBOTICS','The hardest part of a robot hand is the feedback.','A grasp is a loop of perception, movement, and correction. Touch sensing gives machines a way to react when the world does not match the plan.',['Tactile sensing','Control systems'],['AI','XR'],'robot'],
 ['DEV','Local-first software puts the user back in control.','Store the working copy on the device, sync when possible, and keep the core experience usable offline. Distributed state is difficult; waiting for a spinner is easy to avoid.',['Local-first','Architecture'],['STARTUPS','XR'],'code'],
 ['HARDWARE','The data center is an energy system.','An AI workload depends on cooling, power delivery, and grid capacity as much as on chips. Efficiency improvements outside the model can change the economics.',['Energy','Infrastructure','AI inference'],['AI','SCIENCE'],'science'],
 ['XR','A digital twin becomes useful when it can disagree.','A simulation should help us spot the difference between what we expected and what happened. Connecting a model to real observations turns a visualization into a tool.',['Digital twins','Simulation'],['ROBOTICS','SCIENCE'],'spatial'],
 ['STARTUPS','Build around a workflow, not a model release.','Products last when they solve a repeatable problem. Model improvements are an advantage when the product can adopt them without asking the customer to start over.',['Workflows','Product design'],['AI','DEV'],'growth'],
 ['SCIENCE','An open dataset can be as valuable as a new model.','Reproducible measurements let more teams ask better questions. Shared benchmarks help separate a promising demo from progress that others can build on.',['Open science','Datasets'],['AI','DEV'],'science'],
];
const links: Record<Category,string> = {AI:'https://www.anthropic.com/engineering',ROBOTICS:'https://www.nvidia.com/en-us/industries/robotics/',XR:'https://developer.apple.com/visionos/',DEV:'https://github.com/features/copilot',HARDWARE:'https://www.nvidia.com/en-us/data-center/',STARTUPS:'https://www.ycombinator.com/library',SCIENCE:'https://deepmind.google/science/'};
export const posts: Post[] = seeds.map((s,i)=>({id:`demo-${i+1}`,category:s[0],title:s[1],text:s[2],tags:s[3],related:s[4],visual:s[5],author:'Techer editorial',handle:'@techer',initials:'T',source:'Demo collection',url:links[s[0]],quality:0.95-i*0.015,novelty:0.9-i*0.01,publishedAt:'2026-09-22T09:00:00Z'}));
export function affinity(profile:Profile,category:Category) { return Math.max(-3, Math.min(6,(profile.interests.includes(category)?1.3:0)+profile.interactions.reduce((n,e)=>n+(posts.find(p=>p.id===e.postId)?.category===category?({RIGHT:0.7,LEFT:-0.45,SAVE:1.1,OPEN:0.12}[e.action]):0),0))); }
export function rank(profile:Profile,filter:string) { const seen=new Set(profile.interactions.filter(e=>e.action==='RIGHT'||e.action==='LEFT').map(e=>e.postId));return posts.filter(p=>!seen.has(p.id)&&(filter==='ALL'||filter==='BLIND SPOT'||p.category===filter)).map(p=>{const interest=affinity(profile,p.category);const bridge=p.related.reduce((m,c)=>Math.max(m,affinity(profile,c)),0);const blind=p.quality*p.novelty*(1/(1+Math.max(0,interest)))*bridge;return {post:p,score:filter==='BLIND SPOT'?blind:interest+p.quality+p.novelty*.3,bridge,interest};}).filter(p=>filter!=='BLIND SPOT'||(p.bridge>0&&p.interest<1&&p.post.quality>.7)).sort((a,b)=>b.score-a.score).map(p=>p.post); }
